### ISSUE TITLE
连接服务器失败怎么办

### ISSUE THREAD

**Issue by lbyxiaolizi** [Mas0nShi/typoraCracker#10]
RT
![image](https://user-images.githubusercontent.com/65098936/144411261-88e463e5-793a-4b82-8fc4-5a9231351f97.png)

**Comment by Mas0nShi** [comment]
typoraCracker为**解包打包工具**，不提供patch部分支持。

**Comment by tarzanfan** [comment]
现在是不是必须翻墙才能用？国内服务器不能使用吧

**Comment by Mas0nShi** [comment]
> 现在是不是必须翻墙才能用？国内服务器不能使用吧

![image](https://user-images.githubusercontent.com/60805843/155251141-39469a83-0801-4c4f-9e40-ca0ee3f6e4a6.png)

**Comment by tarzanfan** [comment]
> > 现在是不是必须翻墙才能用？国内服务器不能使用吧
> 
> ![image](https://user-images.githubusercontent.com/60805843/155251141-39469a83-0801-4c4f-9e40-ca0ee3f6e4a6.png)

已经解决了。少了一步拷贝cp ./example/patch/License.js ./dec_app/
