### ISSUE TITLE
a javascript error occurred in the main process

### ISSUE THREAD

**Issue by goodtogood** [Mas0nShi/typoraCracker#14]
解包，替换js，打包一切都正确完成，
然后把打包后的app.asar替换到Typora 的resources下，
此时启动程序会报下图中的错误，同时系统中会有多个僵尸进程

OS :  win 8.1 & win 10
typora : v1.0.3

![图片](https://user-images.githubusercontent.com/10088733/144792485-066d43c6-2d33-4661-864b-324d6ce7db28.png)

![图片](https://user-images.githubusercontent.com/10088733/144792772-d89076f8-34e2-47eb-b2af-ddd9505afdf0.png)

**Comment by goodtogood** [comment]
卸载重新装了1.0.2可以正常激活，估计1.0.3有些改动吧
![图片](https://user-images.githubusercontent.com/10088733/144795126-719c854a-7e83-477d-bc5e-53e570c181b5.png)

**Comment by Mas0nShi** [comment]
typoraCracker 仅为解包&打包工具，`example`文件下的内容仅用作示例用途。

**Comment by Mas0nShi** [comment]
经测试win/ubuntu V1.0.3下此工具正常运行。

**Comment by goodtogood** [comment]
谢谢，我再检查一下

**Comment by liangjiahuiLJH** [comment]
> 谢谢，我再检查一下

我今天也遇到这个问题了，我是因为在linux虚拟机执行python命令，linux虚拟机不能直接访问windows文件系统，是拷贝的app.asar文件到linux文件系统来执行python命令，最后再烤回windows目录时就报这个错误；
最后通过多次尝试发现第一个python命令的app.asar文件目录必须在typora安装目录下，可能生成还依赖了该目录下其它文件；
最终在windows系统，使用原始app.asar文件路径（typora安装路径下）可以正常生成。
