### ISSUE TITLE
No module named 'masar'

### ISSUE THREAD

**Issue by 1163175014** [Mas0nShi/typoraCracker#15]
python环境3.8 3.9都试了，requirements.txt里的模块也都装了，但运行还是提示No module named 'masar'，自己谷歌了一下也没找到这是个什么包，麻烦告知一下

**Comment by Mas0nShi** [comment]
[masar.py](https://github.com/Mas0nShi/typoraCracker/blob/master/masar.py)

**Comment by 1163175014** [comment]
> [masar.py](https://github.com/Mas0nShi/typoraCracker/blob/master/masar.py)
我傻了，感谢

**Comment by AirBashX** [comment]
> > [masar.py](https://github.com/Mas0nShi/typoraCracker/blob/master/masar.py)
> > 我傻了，感谢

如何解决?
