### ISSUE TITLE
target new version released

### ISSUE THREAD

**Issue by jammesbon** [Mas0nShi/typoraCracker#16]
the target has released new version,this can't work.
![图片](https://user-images.githubusercontent.com/4210052/145361098-c6617de1-0095-499a-ae22-039938a656be.png)

**Comment by Mas0nShi** [comment]
It seems that it is not the problem with typoraCracker, but that you have deleted the main.node under `app.asar.unpacked`.

**Comment by Mas0nShi** [comment]
do not use the `asar` provided by npm.
plz add param `-u` to pack it.

**Comment by scratchmex** [comment]
I resolved it by packing the asar with the `main.node`

**Comment by Mas0nShi** [comment]
> I resolved it by packing the asar with the `main.node`

Typora puts main.node under `app.asar.unpacked` by default. 
If you add `main.node` to `app.asar`, this will cause `app.asar` to become bigger.

**Comment by jammesbon** [comment]
Closed

**Comment by scratchmex** [comment]
@Mas0nShi for some reason it still does not work if I don't put `main.node` in `app.asar`. Do you know what could be happening? 
@jammesbon How did you solve it?

**Comment by Mas0nShi** [comment]
> @Mas0nShi for some reason it still does not work if I don't put `main.node` in `app.asar`. Do you know what could be happening?
> @jammesbon How did you solve it?

the `main.node` under `app.asar.unpacked`, you can reinstall if you can't find it.
