### ISSUE TITLE
 typora v1.0.3

### ISSUE THREAD

**Issue by Shenlong616** [Mas0nShi/typoraCracker#21]
![dd](https://i.ibb.co/WK5152P/Capture.png)

**Comment by Shenlong616** [comment]
not working :(

**Comment by Mas0nShi** [comment]
i think you should read README.md/Usage first.
in addition, i don't provide patch by version 1.0.3, if you want to crack typora v1.0.3 you should patch by yourself.

**Comment by Shenlong616** [comment]
i don't have typora v1.0.0.exe installation file :)
can you share that installation file for everyone?

Thank you!

**Comment by sehowyoung** [comment]
you can download 1.02 in its official website

**Comment by Mas0nShi** [comment]
> 

https://typora.io/releases/all

**Comment by Shenlong616** [comment]
@sehowyoung
@Mas0nShi

![](https://i.ibb.co/LYZPPrC/Capture.png)

v1.0.2 still not working :(

**Comment by Mas0nShi** [comment]
> @sehowyoung @Mas0nShi
> 
> ![](https://camo.githubusercontent.com/f4ce5168d85e7d36f0155e240c9c8dad12aa977b1429f428f712fa9940f858fc/68747470733a2f2f692e6962622e636f2f4c595a505072432f436170747572652e706e67)
> 
> v1.0.2 still not working :(

did you replace the Lisence.js?

**Comment by Shenlong616** [comment]
@Mas0nShi no?

**Comment by Mas0nShi** [comment]
> @Mas0nShi no?

plz give a full command screenshot.

**Comment by Shenlong616** [comment]
v1.0.2

![](https://i.ibb.co/CJyxQjr/1.png)
![](https://i.ibb.co/8x7srWw/2.png)
![](https://i.ibb.co/Tkz9hYB/3.png)
![](https://i.ibb.co/HLv3nk6/4.png)

im right @Mas0nShi?

**Comment by Shenlong616** [comment]
https://i.ibb.co/Tkz9hYB/3.png

**Comment by sehowyoung** [comment]
i think you can try it: https://ghpym.lanzoui.com/iqcgkxdfmle.
it has been cracked!

**Comment by Mas0nShi** [comment]
before `python typora.py -u workstation/outfile/dec_app workstation/outappasar`, you should replace [License.js](https://github.com/Mas0nShi/typoraCracker/blob/master/example/patch/License.js) to `/workstation/outfile/dec_app/Liscence.js` first.

**Comment by Mas0nShi** [comment]
you need replace to `resources/app.asar`  not `app.asar`

**Comment by Shenlong616** [comment]
I'm busy right now, I'll check back tomorrow

Thank you both for your support @sehowyoung @Mas0nShi
