### ISSUE TITLE
最新版本1.0.3已失效，希望能尽快更新！！！

### ISSUE THREAD

**Issue by x88xx** [Mas0nShi/typoraCracker#24]
最新版本1.0.3已失效，希望能尽快更新！！！

**Comment by DroidKali** [comment]
并没有失效，是你方法不对

**Comment by Mas0nShi** [comment]
截至目前typora v1.0.3，typoraCracker解包&打包功能一切正常。提供的example仅用于示例，并不保证新版本适用。

**Comment by hui-shao** [comment]
1.0.3 的确正常 我目前就在用

**Comment by tarzanfan** [comment]
如果使用国内服务器是不是无法激活。现在国外服务器已经被墙了吧

**Comment by tarzanfan** [comment]
deepin   + typore1.0.3 激活成功了。参考https://jckling.github.io/2021/12/24/Other/Typora%20%E6%BF%80%E6%B4%BB%E6%95%99%E7%A8%8B/
