### ISSUE TITLE
1.1.2解包错误

### ISSUE THREAD

**Issue by mxlt02** [Mas0nShi/typoraCracker#28]
![image](https://user-images.githubusercontent.com/57489136/154641814-f321282b-1965-4077-a848-298b68337a2c.png)
这是结果

**Comment by liuluping0106** [comment]
同问

**Comment by Mas0nShi** [comment]
I can tell you no problem for typoraCracker.
You need read atom.js carefully, plz.

**Comment by Mas0nShi** [comment]
https://github.com/Mas0nShi/typoraCracker/issues/29#issuecomment-1045995106

**Comment by Delppine1024** [comment]
https://github.com/SnapdragonLee/TyporaCrack
