### ISSUE TITLE
1.1.3-1 版本已失效

### ISSUE THREAD

**Issue by lzscxb** [Mas0nShi/typoraCracker#29]
Archlinux typora1.1.3-1 
增加了离线激活
![image](https://user-images.githubusercontent.com/58434904/154794507-c4e60188-f1ed-4593-a2cb-ec3f34614f0a.png)

**Comment by Mas0nShi** [comment]
参见 #25

**Comment by lzscxb** [comment]
typora1.1.3是正常的，刚刚更新的1.1.3-1失效
![image](https://user-images.githubusercontent.com/58434904/154795725-23824475-6c6c-44e0-9609-c1242edb67f4.png)

**Comment by Mas0nShi** [comment]
方便提供下archive吗

**Comment by lzscxb** [comment]
https://aur.archlinux.org/packages/typora

git clone https://aur.archlinux.org/typora.git 


昨日更新

**Comment by Mas0nShi** [comment]
> https://aur.archlinux.org/packages/typora
> 
> git clone https://aur.archlinux.org/typora.git
> 
> 昨日更新

typoraCracker工作正常，且解包内容似乎与1.1.3无区别

**Comment by Mas0nShi** [comment]
all going well
![](https://i.imgur.com/80CEH9W.png)

**Comment by YRSB** [comment]
Arch Linux Typora1.1.3-1
我也遇到了跟你相同的问题

**Comment by lzscxb** [comment]
> 我也遇到了跟你相同的问题

只能先降级使用了

**Comment by Vzz1c** [comment]
> 一切顺利 ![](https://camo.githubusercontent.com/9d8caf92bc4ff02eb11e12a47fe304f1d34821200635130721a67e8861375143/68747470733a2f2f692e696d6775722e636f6d2f383043454839572e706e67)

license.js无效了,大佬给个最新版atom.js,非常感谢1550287628@qq.com

**Comment by Mas0nShi** [comment]
> > 一切顺利 ![](https://camo.githubusercontent.com/9d8caf92bc4ff02eb11e12a47fe304f1d34821200635130721a67e8861375143/68747470733a2f2f692e696d6775722e636f6d2f383043454839572e706e67)
> 
> license.js无效了,大佬给个最新版atom.js,非常感谢[1550287628@qq.com](mailto:1550287628@qq.com)

不提供修改支持。参见#25

**Comment by likeya** [comment]
新版本1.1.4解压包后，只有3个文件：atom、main、package.json，用原来替换License.js的方式并不能Crack了，楼主能Crack成功?是修改了其他文件吧？

> all going well ![](https://camo.githubusercontent.com/9d8caf92bc4ff02eb11e12a47fe304f1d34821200635130721a67e8861375143/68747470733a2f2f692e696d6775722e636f6d2f383043454839572e706e67)

**Comment by Mas0nShi** [comment]
> 新版本1.1.4解压包后，只有3个文件：atom、main、package.json，用原来替换License.js的方式并不能Crack了，楼主能Crack成功?是修改了其他文件吧？
> 
> > all going well ![](https://camo.githubusercontent.com/9d8caf92bc4ff02eb11e12a47fe304f1d34821200635130721a67e8861375143/68747470733a2f2f692e696d6775722e636f6d2f383043454839572e706e67)

不会透露如何crack，我只能说你们不够仔细，但凡你们能仔细点也不至于一大堆人跑过来跟我说失效

不要再问我如何crack，我不提供思路、成品

**Comment by Delppine1024** [comment]
https://github.com/SnapdragonLee/TyporaCrack
