### ISSUE TITLE
version 1.1.3 not support

### ISSUE THREAD

**Issue by avboy1337** [Mas0nShi/typoraCracker#30]
version 1.1.2 not support
3ks for your work!

**Comment by Mas0nShi** [comment]
> version 1.1.2 not support 3ks for your work!

oh, my bro. plz read #25 first !

**Comment by Mas0nShi** [comment]
Recently, many people asked this question.
I tested 1.1.3-1 for Ubuntu and 1.1.3 for Windows (lastest version), the result is all worked well.
It's just that the example I provided doesn't work.

**Comment by avboy1337** [comment]
going to have one more time to check .

**Comment by Mas0nShi** [comment]
> 又测试了下，之前旧版可以，我测试最新win下不成功。 步过老哥测试成功，我也没别的说的了。关闭issue了。

我不理解你们说的不能用是指什么...

![image](https://user-images.githubusercontent.com/60805843/154847861-2ef63ae6-aec3-4b07-bce8-076fb8ce6ffd.png)

**Comment by avboy1337** [comment]
明天问同事，哈哈。你牛逼！！

**Comment by xzchina** [comment]
1.1.3 改服务器在线验证了. 而且加入了离线激活, 的确无法注册成功.
