### ISSUE TITLE
Windows下的1.1.4版本失效了

### ISSUE THREAD

**Issue by visualwind** [Mas0nShi/typoraCracker#31]
https://typora.io/windows/typora-setup-x64.exe
hash: "f813469903c7106408e85cacc0e1d8d5c3ad51190e308eff6e9f0f2e67a6b2d9"

**Comment by visualwind** [comment]
https://typora.io/windows/typora-setup-x64.exe
"hash": "f813469903c7106408e85cacc0e1d8d5c3ad51190e308eff6e9f0f2e67a6b2d9"

**Comment by avboy1337** [comment]
老哥确定？

**Comment by RomelSan** [comment]
There is an activate offline too.

**Comment by avboy1337** [comment]
我上次提issue，1.1.3版本，作者已经测试过了OK的。不过我确实一直没测试激活成。一会儿看看1.1.4去试试

**Comment by Mas0nShi** [comment]
the lastest version: 1.1.5 测试通过

**Comment by zhangleijuly** [comment]
没有失效，作者在[#25](https://github.com/Mas0nShi/typoraCracker/issues/25)其实已经说明了，本项目只是示例，软件有改动就没法无脑套用。
1.1.4版本相比1.0.3版本修改了文件结构，并且把变量名都改成业务无关的了，有一定代码基础仿照示例修改还是有效的。
![2022-02-22_095907](https://user-images.githubusercontent.com/1475065/155049493-78946738-b59b-4498-9967-4e4ffc59fc5f.png)
![2022-02-22_095952](https://user-images.githubusercontent.com/1475065/155049503-e09e53b3-2527-4725-9e35-afa8be14dcbe.png)

**Comment by Ryanjiena** [comment]
今早更新的 1.1.5 版本还能用

 ![image](https://user-images.githubusercontent.com/43134606/155062878-e14699bd-506f-4863-95f6-e91cbb9e9b97.png)

**Comment by wangchenxi99** [comment]
> 今早更新的1.1.5版本可以使用
> 
> ![图片](https://user-images.githubusercontent.com/43134606/155062878-e14699bd-506f-4863-95f6-e91cbb9e9b97.png)

需要修改代码么

**Comment by wangchenxi99** [comment]
> 

试了一下旧的代码不好用了

**Comment by Ryanjiena** [comment]
> > 今早更新的1.1.5版本可以使用
> > ![图片](https://user-images.githubusercontent.com/43134606/155062878-e14699bd-506f-4863-95f6-e91cbb9e9b97.png)
> 
> 需要修改代码么

根据 `{UsersRoot}\AppData\Roaming\Typora\typora.log` 修改 `workstation/outfile/dec_app` 里的代码，新版的变量名被换了，可以参考之前的版本修改

**Comment by Ryanjiena** [comment]
> > 
> 
> 试了一下旧的代码不好用了

看 readme 和 #25 里的说明

**Comment by Aronlele** [comment]
> 

出个教程啊

**Comment by zdhsoft** [comment]
> 今早更新的 1.1.5 版本还能用

我一直没有试成功。我也更新了最新的代码。

**Comment by Ryanjiena** [comment]
> > 今早更新的 1.1.5 版本还能用
> 
> 我一直没有试成功。我也更新了最新的代码。


仔细看 readme 

```bash
patch code by yourself in workstation/outfile/dec_app)
```

typoracrack 现只提供解包打包，具体 crack 需要修改 workstation/outfile/dec_app 里的代码

**Comment by Aronlele** [comment]
大神，能教学下不

Ryanjiena ***@***.***> 于2022年2月24日周四 15:37写道：
