### ISSUE TITLE
版本1.1.5解包漏文件

### ISSUE THREAD

**Issue by MirionQs** [Mas0nShi/typoraCracker#35]
版本1.1.5中app.asar中有三个文件，解包时main.node漏了，我从别的地方挪来一个main.node打包时也漏了
![Snipaste_2022-03-06_02-48-56](https://user-images.githubusercontent.com/51433180/156896379-4ff8c58b-893f-4caa-a7d0-6fc6f013b451.jpg)

**Comment by Mas0nShi** [comment]
typora安装后自动将main.node解压，且main.node拥有`unpacked: True`属性，属于正常情况。

**Comment by MirionQs** [comment]
> typora安装后自动将main.node释放，且main.node拥有`unpacked: True`属性，属于正常情况。 如若强制打包，除了增大体积，其他并无他用。

解包

![1](https://user-images.githubusercontent.com/51433180/156909985-34cfaf56-76c8-4942-923e-07e2f023fdbb.jpg)

将dec-app里的js文件不做修改移至out文件夹里打包

![2](https://user-images.githubusercontent.com/51433180/156909997-d5475a50-aaa7-4ef6-bceb-2a14c5420661.jpg)

得到app.asar替换掉typora/resources里的app.asar，运行typora报错

![3](https://user-images.githubusercontent.com/51433180/156910025-e1f443e2-eaae-40c9-91f0-ba16a5c64cd6.jpg)

**Comment by MirionQs** [comment]
typora表示找不到main.node，我除去app.asar外的typora文件都没有动过

**Comment by Mas0nShi** [comment]
> typora表示找不到main.node，我除去app.asar外的typora文件都没有动过

建议重新安装……app.asar中本身并不包含main.node

**Comment by MirionQs** [comment]
> > typora表示找不到main.node，我除去app.asar外的typora文件都没有动过
> 
> 建议重新安装……app.asar中本身并不包含main.node，对此，该项目无能无力

经过上面的处理后app.asar的文件大小变小了1KB（而我并没有做改动），我试试对比之间的差别。

**Comment by Mas0nShi** [comment]
如果你意图diff这1kb证明存在main.node，我不认为现代编译器能够编译得到1kb的可执行文件（

**Comment by MirionQs** [comment]
> 如果你意图diff这1kb证明存在main.node，我不认为现代编译器能够编译得到1kb的可执行文件（

我想是否是少了某些数据导致typora找不到main.node，我也不觉得main.node的大小就占1kb（

**Comment by fys666** [comment]
我也遇到了相同的问题，我今天刚下载的最新版

**Comment by fys666** [comment]
> > 如果你意图diff这1kb证明存在main.node，我不认为现代编译器能够编译得到1kb的可执行文件（
> 
> 我想是否是少了某些数据导致typora找不到main.node，我也不觉得main.node的大小就占1kb（

我也遇到了相同的问题，请问你后续是如何解决的

**Comment by MirionQs** [comment]
> > > 如果你意图diff这1kb证明存在main.node，我不认为现代编译器能够编译得到1kb的可执行文件（
> > 
> > 
> > 我想是否是少了某些数据导致typora找不到main.node，我也不觉得main.node的大小就占1kb（
> 
> 我也遇到了相同的问题，请问你后续是如何解决的

https://github.com/SnapdragonLee/TyporaCrack
这里有成功修改的，我就直接用了

**Comment by fys666** [comment]
> > > > 如果你意图diff这1kb证明存在main.node，我不认为现代编译器能够编译得到1kb的可执行文件（
> > > 
> > > 
> > > 我想是否是少了某些数据导致typora找不到main.node，我也不觉得main.node的大小就占1kb（
> > 
> > 
> > 我也遇到了相同的问题，请问你后续是如何解决的
> 
> https://github.com/SnapdragonLee/TyporaCrack 这里有成功修改的，我就直接用了

请问你是直接用的什么文件呢？你是直接下载了他的app.asar然后运行node example/keygen.js的吗？
