### ISSUE TITLE
执行语句失败

### ISSUE THREAD

**Issue by ZHR-BLACK** [Mas0nShi/typoraCracker#37]
![image](https://user-images.githubusercontent.com/22974353/159610520-1ad82d69-9245-4563-a10e-760e3fcade91.png)

**Comment by Mas0nShi** [comment]
请使用python3.6+

**Comment by YuqinXu1218** [comment]
node : The term 'node' is not recognized as the name of a cmdlet, function, script file, or ope
rable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.

**Comment by YuqinXu1218** [comment]
> 

The problem has been solved.Thank you very much!
