### ISSUE TITLE
1.2.3 又一次解密失败

### ISSUE THREAD

**Issue by Delppine1024** [Mas0nShi/typoraCracker#38]
https://typora.io/windows/typora-setup-x64.exe?0321

貌似每一次更新，都会将iv等信息固定，导致解密失败

Console:
Traceback (most recent call last):
  File "typora.py", line 182, in <module>
    main()
  File "typora.py", line 177, in main
    args.mode(args.asarPath, args.dirPath, args.format)
  File "typora.py", line 95, in extractWdec
    scode = decScript(scode, prettify)
  File "typora.py", line 52, in decScript
    code = unpad(ins.decrypt(cipherText), 16, 'pkcs7')
  File "C:\ProgramData\Anaconda3\envs\typora_cracker\lib\site-packages\Crypto\Util\Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")

看样子每次都需要进行重复的工作。

**Comment by wds-job** [comment]
遇到同样问题，破解失败，这个版本加了图片删除功能，很好用，希望能早点破解

**Comment by Mas0nShi** [comment]
目前还没有找到比较好的办法实现自动化部署，近期会手动建立1.2.3版本分支暂时解决该问题。

**Comment by Delppine1024** [comment]
或许可以把这些校验信息放到release内，对应每一个tag

**Comment by byebvip** [comment]
看了一下,决定还是入手正版.价格不贵

**Comment by Mas0nShi** [comment]
此版本分支已更新
https://github.com/Mas0nShi/typoraCracker/tree/1.2.3_windows

**Comment by wds-job** [comment]
我尝试了下 v1.2.3-x86-win 这个版本，貌似还不能解压app.asar文件，望大佬修复

**Comment by Delppine1024** [comment]
在linux x64 1.2.3 也出现了同样的问题，padding incorrect

**Comment by Mas0nShi** [comment]
> 我尝试 v1.2.3-x86-win 这个版本，貌似还不能解压app.asar文件，望大佬修复

我这里测试解包正常

**Comment by Mas0nShi** [comment]
> 在linux x64 1.2.3 也出现了同样的问题，padding incorrect

linux x64 1.2.3请使用main分支

**Comment by Delppine1024** [comment]
> > 在linux x64 1.2.3 也出现了同样的问题，padding incorrect
> 
> linux x64 1.2.3请使用main分支

不行，我尝试了一下，并不可以
