### ISSUE TITLE
in typora for Windows and Linux, AES key and iv generate random now.

### ISSUE THREAD

**Issue by Mas0nShi** [Mas0nShi/typoraCracker#39]
I am sorry to inform you that typoraCracker has been discontinued for maintenance, as the title says, there is no point in duplicating work and this tool will no longer be adapted to new versions until a new method is found.

**Comment by Vittorio-Veneto-www** [comment]
So the cracker is currently unusable?

**Comment by Mas0nShi** [comment]
> So the cracker is currently unusable?

no, need to analyze each version of binary to get the aes key and iv if still use unpack method.
So I didn't find a better way to automate deployment (get the aes key and iv).
Maybe we have go another way to achieve crack.
I am thinking about stopping the maintenance typoraCracker now, because it's seems like meaningless.

**Comment by Delppine1024** [comment]
> > So the cracker is currently unusable?
> 
> 
> 
> no, need to analyze each version of binary to get the aes key and iv if still use unpack method.
> 
> So I didn't find a better way to automate deployment (get the aes key and iv).
> 
> Maybe we have go another way to achieve crack.
> 
> I am thinking about stopping the maintenance typoraCracker now, because it's seems like meaningless.

emm，可以询问一下AES和iv的信息隐藏在哪里么

**Comment by Mas0nShi** [comment]
> > > So the cracker is currently unusable?
> > 
> > 
> > no, need to analyze each version of binary to get the aes key and iv if still use unpack method.
> > So I didn't find a better way to automate deployment (get the aes key and iv).
> > Maybe we have go another way to achieve crack.
> > I am thinking about stopping the maintenance typoraCracker now, because it's seems like meaningless.
> 
> emm，可以询问一下AES和iv的信息隐藏在哪里么

you can see my article about how to get the aes key and iv: https://blog.shi1011.cn/rev/1891
and some refer issue: #26

**Comment by Delppine1024** [comment]
OK I have seen about  the getting-way, but just so complicated. So you get it manually, every time when there is a new version updated?

**Comment by Z00M-Team** [comment]
Right now.

**Comment by Mas0nShi** [comment]
> OK I have seen about the getting-way, but just so complicated. So you get it manually, every time when there is a new version updated?

yes, i don't find the useful method to solve it at least now.

**Comment by Delppine1024** [comment]
I have find a way, the 3 OS-Platform version have a constant KEY location, which can be found in `main.node`. But, this is just an alternative way which cannot apply when the code change the format. BTW, you can memorize the offset of each version, then read the located content. Maybe there are some remark code in bin-read mod, but I can't assure where/what it is. You can use this method at present, but Must reanalyze the stack when you read the KEY-location content and get a wrong KEY.

**Comment by Mas0nShi** [comment]
> I have found a way, the 3 OS-Platform version have a constant KEY location, which can be found in `main.node`. But, this is just an alternative way which cannot apply when the code change the format. BTW, you can memorize the offset of each version, then read the located content. Maybe there are some remark code in bin-read mod, but I can't assure where/what it is. You can use this method at present, but Must reanalyze the stack when you read the KEY-location content and get a wrong KEY. I found the right key by using this method, v1.2.4

Can give an example of a feature or more detail ?

**Comment by Delppine1024** [comment]
For Windows x64 1.2.3, the IV location in Sublime Text:
![image-20220328103058753](https://user-images.githubusercontent.com/100767917/160782327-72375f65-42f9-4d1f-9e1c-7a535f5222f8.png)

the AES location in Sublime Text:
![image-20220328103516892](https://user-images.githubusercontent.com/100767917/160782579-084cf669-681d-4115-967e-997475e09c7c.png)

**Comment by Delppine1024** [comment]
> > For Windows x64 1.2.3, the IV location in Sublime Text: ![image-20220328103058753](https://user-images.githubusercontent.com/100767917/160782327-72375f65-42f9-4d1f-9e1c-7a535f5222f8.png)
> > the AES location in Sublime Text: ![image-20220328103516892](https://user-images.githubusercontent.com/100767917/160782579-084cf669-681d-4115-967e-997475e09c7c.png)
> > The same location in v1.2.4
> 
> ok, it's random RVA when the sources compiled, you can see the aes iv and key all be inline, not constant. i see that the feature you searched for used the old aes key or iv, but that doesn't quite work if he completely changed the key and iv.

well, I don't know how it was generated, but you can memorize this location. So, you "Must reanalyze the stack when you read the KEY-location content and get a wrong KEY".

**Comment by Mas0nShi** [comment]
> well, I don't know how it was generated, but you can memorize this location. So, you "Must reanalyze the stack when you read the KEY-location content and get a wrong KEY".

maybe we should give up this expired repo.

**Comment by Mas0nShi** [comment]
see the new method of "inject code": https://github.com/Yoshino-s/typoraCracker
it's a good solution.

**Comment by Mas0nShi** [comment]
I am trying to use radare2 to automatically analyze the binaries for AES key and iv, but this is experimental (testing only).
