### ISSUE TITLE
使用最新的x64 版本 生成出序列号不正确

### ISSUE THREAD

**Issue by publicDayJAVA** [Mas0nShi/typoraCracker#42]
![image](https://user-images.githubusercontent.com/29913732/160069764-49ddbca4-d0d6-4c58-85a8-18934ce0893c.png)
使用
![image](https://user-images.githubusercontent.com/29913732/160069825-4ab85109-66a8-48ff-9ab1-2a6c95c6375d.png)
生成出的序列号。
使用版本，1.2.3，python 3.10.3

操作过程中发现 生成dec_app 文件夹中文件比较少，没有License.js，只有别的三个文件，不知道操作是否正确。

**Comment by Mas0nShi** [comment]
无效issue #25
