### ISSUE TITLE
输入序列号

### ISSUE THREAD

**Issue by dingiso** [Mas0nShi/typoraCracker#5]
抱歉我是新手，请问在最后一步打开typora后，需要在hosts 添加些什么么
我是在试用阶段破解的，需要重新下载一下么
我输入序列号后显示 请输入正确的序列号
OS ： win11
typora： 1.0.2
![image](https://user-images.githubusercontent.com/43989619/144179870-7909b880-1fa7-4ec7-8689-3192a3321e0b.png)

**Comment by Mas0nShi** [comment]
要注意的是，本开源项目不公开破解流程及思路。

**Comment by dingiso** [comment]
sorry , 马上run去支持正版
